stages:
  data_ingestion:
    cmd: python src/deepClassifier/pipeline/data_ingestion_stage.py
    deps:
      - src/deepClassifier/pipeline/data_ingestion_stage.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages


  prepare_base_model:
    cmd: python src/deepClassifier/pipeline/prepare_base_model.py
    deps:
      - src/deepClassifier/pipeline/prepare_base_model.py
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/deepClassifier/pipeline/training.py
    deps:
      - src/deepClassifier/pipeline/training.py
      - src/deepClassifier/components/prepare_callback.py
      - configs/config.yaml
      - artifacts/data_ingestion/PetImages
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/deepClassifier/pipeline/evalution_stage.py
    deps:
      - src/deepClassifier/pipeline/evalution_stage.py
      - configs/config.yaml
      - artifacts/data_ingestion/PetImages
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false
        